version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-pii-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fb2ol2ag2f0s"
s3_prefix = "user-pii-demo"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserServiceKeyAliasName=\"alias/userservicekey\""
image_repositories = []
